#2163 Add Basic HTTP Authentication (encrypted) support for Open Distro
Smile-SA/elasticsuite pull request #2167
Opened 2021-06-10 13:21 UTC by kdckrs

2021-06-21 12:22 UTC, romainruaud requested changes
Could you please also add an adminhtml field (Yes/No) to specify if encrypted authentication should be use ?

2021-06-21 12:22 UTC, romainruaud commented on src/module-elasticsuite-core/Client/ClientBuilder.php
> +        'http_auth_encrypted'   => null,
`http_auth_encrypted` here but `http_auth_encoded` below.

2021-06-21 12:22 UTC, romainruaud commented on src/module-elasticsuite-core/Client/ClientBuilder.php
> +        if (!empty($options['http_auth_user']) && !empty($options['http_auth_pwd']) && $options['http_auth_encoded']) {
`http_auth_encoded` here but `http_auth_encrypted` above.

2021-06-29 14:02 UTC, kdckrs commented
> Could you please also add an adminhtml field (Yes/No) to specify if encrypted authentication should be use ?

Cheers for reviewing! I have made the corrections and added the ability to configure this in the admin area. Please let me know if any additional changes are required.

Thanks!

2021-06-30 06:32 UTC, kdckrs reviewed
Edit: woops double comment

2021-06-30 07:56 UTC, romainruaud commented
Great, thank you for updating this.

I cannot test it by myself (no Open Distro environment with password protection), but I guess you tested it prior to pushing ?

Regards

2021-06-30 08:02 UTC, kdckrs commented
> Great, thank you for updating this.
> 
> I cannot test it by myself (no Open Distro environment with password protection), but I guess you tested it prior to pushing ?
> 
> Regards

Yes I have tested it before pushing. If you want we can arrange a quick call to go over it?

2021-06-30 08:04 UTC, merged