Fixes #2172, add rel=nofollow in layered navigation links
Smile-SA/elasticsuite pull request #2175
Opened 2021-06-16 14:17 UTC by vahonc

2021-07-05 07:55 UTC, romainruaud commented
@vahonc can you make it configurable ? It would be nice to have a switch for each attribute where user can select the value of "follow", "nofollow" for each attribute ?

2021-07-09 08:11 UTC, romainruaud commented
To clarify, what I'd like to have is : 

In Back-Office : 

- a new field for each attribute edit screen.
- the field is named "Meta Robots" (meta_robots), that will have this options : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Config/Model/Config/Source/Design/Robots.php
- the default value is "INDEX, FOLLOW".
- this field is displayed only if the attribute is "is_filterable" or "is_filterable_in_search"

In Front-Office : 
- apply the proper value to the html rendering from the attribute data (as it's done for "facet_max_size" or "facet_sort_order".

(Bonus) In GraphQL : 
- add a field "meta_robot" in the Aggregations, like it's done for the "has_more" here : https://github.com/Smile-SA/elasticsuite/commit/7e18e2504a08bee1b84a6e95f51e68bdb0e32866

2021-09-14 12:45 UTC, romainruaud requested changes

2021-09-14 12:45 UTC, romainruaud commented on src/module-elasticsuite-catalog/Setup/CatalogSetup.php
> +                'comment'  => 'Boolean logic to use for displaying rel="nofollow" attribute for all filter links of current attribute',
The comment is not accurate :) it looks like a copy-paste :)

2021-09-14 12:45 UTC, romainruaud commented
please fix the requested changes and also the PHPMD, and we'll be good to merge

2021-09-17 14:02 UTC, merged

2022-08-14 06:38 UTC, CalzaFino commented
Can you please confirm if this feature was implemented? I did update to the newest version (2.10.11) but I can't find anywhere the menu to set the noindex. I do have several filtrable attributes and this option is not visible.
Thank you for all your hard work providing this module.

2022-08-15 06:54 UTC, vahonc commented
Hello @CalzaFino,

In order to see this field, you need to set the value `Filterable (with results)` for the option `Use in Layered Navigation` on the `Storefront Properties` tab. And this is a prerequisite. 

Look at the screenshot below:

![Screenshot from 2022-08-15 09-36-54](https://user-images.githubusercontent.com/67791361/184588603-b8b98a57-9288-4c09-a9f5-e7ee992efcae.png)

As you can see the field `Add rel="nofollow" to filter links in Layered Navigation`will be displayed right after the field `Use in Layered Navigation`.

BR,
Vadym