Make use of display_pattern on Product Frontend View
Smile-SA/elasticsuite pull request #3039
Opened 2023-09-03 10:15 UTC by ecrocombe

implementation of #3038 

### 1: Change the attribute display value available to the template 

Override Class Method `Magento\Catalog\Block\Product\View\Attributes::getAdditionalData` and add :
<code>elseif (is_numeric($value) && str_contains($attribute->getData('display_pattern') ?? '','%s')){
                    $value = sprintf($attribute->getData('display_pattern'),$value);
                }</code>

### 2: Use newly created block in product view page
Reference existing Block class and change to new block class
`<referenceBlock name="product.attributes" class="Smile\ElasticsuiteCatalog\Block\Product\View\Attributes"/>`

NOTE: I don't believe that `#2` is the correct way about using the new block class. I tried to create a preference in both `di.xml` and `frontend/di.xml` (`<preference for="Magento\Catalog\Block\Product\View\Attributes" type="Smile\ElasticsuiteCatalog\Block\Product\View\Attributes"/>`) but it didn't work, I'm not sure if this is my installation or not.

2023-09-05 07:30 UTC, rbayet commented
Hello @ecrocombe,

I wouldn't go the way of a block override, considering `\Magento\Catalog\Block\Product\View\Attributes` is flagged as `@api`.

Could you re-implement this with an "after" plugin ?

Instead of looping again on the list of product attributes, though, I would probably inject an attribute collection allowing to get the list of attributes for that product that are 
* visible in frontend 
* having a non-void display pattern

Also, considering not everyone would want the feature enabled by default, could you add a Yes/No store configuration setting somewhere below smile_elasticsuite_catalogsearch_settings/catalogsearch ?

Regards,

2023-09-05 15:24 UTC, ecrocombe commented
Hello @rbayet 

I will look into using a plugin. 

I did consider having a configuration yes/no for this, however by setting the `display_pattern` on an attribute to:
-  '%s GB' = yes 
- '%s' = no

is, in its own right, a yes/no configuration? although, not store scoped. Please correct me if I'm wrong, it's currently enabled by default on the layered navigation, and I cannot come up with a scenario where a user would want it in layered navigation but not on product page?

I'm also working on this for the product compare page, can any think of somewhere else on the frontend where display_pattern should be used?

2023-09-05 16:03 UTC, ecrocombe commented
Thank you for taking the time and clearing that up for me, I will go back to the drawing board and add your suggested changes.

2023-09-12 04:46 UTC, ecrocombe commented
Ready for review/approval

2023-09-12 06:33 UTC, rbayet commented
> Ready for review/approval

Hello @ecrocombe,

Thanks for updating the PR.
Could you fix the PHPCS issues pointed out by the "PHP Code Quality" runner (https://github.com/Smile-SA/elasticsuite/actions/runs/6154992630/job/16701201842?pr=3039) ?

Regards

2023-09-12 09:09 UTC, ecrocombe commented
I have cleaned this up as much as I can, the remaining errors say they can be auto fixed? 

Mainly having trouble with the combination of these 3 rules AND the use of coalescing on multiple lines, They seem to conflict each other making a solution impossible, at least to my best abilities.
1. Line char/column maximum count.
2. the char `?` must be **pre**fixed with a space, newline found.
3. the char `?` must be **su**ffixed with a space, newline found.

2023-09-12 09:16 UTC, rbayet commented
Hello @ecrocombe,

Let me check the remaining rules and get back to you with a solution.

Regards,

2023-09-12 09:26 UTC, rbayet requested changes

2023-09-12 09:27 UTC, rbayet commented
Hello @ecrocombe,

Please find the suggestions above.

Regards,

2023-09-12 11:52 UTC, ecrocombe commented
Thank you @rbayet for walking me through this PR. 

If you haven't already noticed, this is my first contribution to a Git project, and I appreciate the time you have taken to educate me.

All the best,

2023-09-12 15:48 UTC, closed without merging

2023-09-12 15:50 UTC, rbayet commented
Hmmm... something strange happenedd locally.

2023-09-12 15:56 UTC, rbayet commented
OK @ecrocombe, that's weird, I rebased your branch locally on top of 2.11.x and squashed the commit, but I mistakenly (force) pushed this repository 2.11.x on top of you 2.11.x branch.
Yet, I cannot re-force push the correct branch.
Anyway, I've created the new PR with your code here : https://github.com/Smile-SA/elasticsuite/pull/3047

2023-09-12 16:57 UTC, rbayet commented
If you want @ecrocombe, you can 
* add my fork as a new remote with `git remote add rbayet git@github.com:rbayet/elasticsuite.git`
* do a `git fetch rbayet` then checkout the branch `ecrocombe-2.11.x` with `git checkout ecrocombe-2.11.x`
* and then push this branch in your own fork with `git push origin ecrocombe-2.11.x` (if "origin" is the name of your remote)

You'll be able to create a new PR with the same code as #3047 but get the badge once I merge it.

Regards,