Add Support for OpenSearch Settings in Setup ConfigOptions List
Smile-SA/elasticsuite pull request #3327
Opened 2024-07-16 21:24 UTC by macoaure

This pull request introduces support for configuring OpenSearch settings within the Setup ConfigOptions list in ElasticSuite. By adding this feature, users can now specify OpenSearch-specific configurations, enhancing the flexibility and compatibility of ElasticSuite with OpenSearch.

2024-07-18 08:01 UTC, romainruaud commented on src/module-elasticsuite-core/Setup/ConfigOptionsList.php
> +    const INPUT_KEY_ES_SSL = 'es-enable-ssl';
Don't change this cosmetic, we like things aligned, and changing these lines is not related to your PR.

2024-07-18 08:01 UTC, romainruaud commented on src/module-elasticsuite-core/Setup/ConfigOptionsList.php
> +    const CONFIG_PATH_ES_SSL = self::CONF_PREFIX . '/enable_https_mode';
Don't change this cosmetic, we like things aligned, and changing these lines is not related to your PR.

2024-07-18 08:01 UTC, romainruaud commented on src/module-elasticsuite-core/Setup/ConfigOptionsList.php
> +        $this->clientBuilder = $clientBuilder;
Don't change this cosmetic, we like things aligned, and changing these lines is not related to your PR.

2024-07-18 08:03 UTC, romainruaud requested changes
Looks good to me except the cosmetic changes in code alignment that I'd like to be removed.

Regards

2024-08-01 09:15 UTC, romainruaud commented
@macoaure can you please update your PR ?

Regards

2024-08-01 12:38 UTC, macoaure commented
hey @romainruaud sorry for my delay, i have fixed the coding standard.

2024-08-18 06:54 UTC, rbayet approved these changes

2024-08-18 06:57 UTC, merged